name: pizza-g2q-benchmarks
version: 0.1.0.0
synopsis: G2Q Benchmark set for Pizza
description: Example symbolic DSLs for benchmarking purpose
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: Sirui Lu (siruilu@cs.washington.edu)
license: BSD3
license-file: LICENSE
github: lsrcz/pizza-haskell
copyright: "2021-2022 Sirui Lu"

dependencies:
- base > 4.14 && < 5
- pizza == 0.1.0.0
- mtl >= 2.2.2
- transformers >= 0.5.6.2
- bytestring >= 0.10.12
- hashable >= 1.3
# - template-haskell >= 2.16
# - th-lift-instances >= 0.1.16
# - unordered-containers >= 0.2.11
# - megaparsec >= 8
# - parser-combinators >= 1
# - timeit >= 1.0
- clock >= 0.7.1
- formatting >= 6.3.1
# - deepseq >= 1.4.4
# - generic-deriving >= 1.14.1
- text >= 1.2.4.1
# - th-compat >= 0.1.2
# - natural-transformation >= 0.3
# - extra >= 1.7.7
# - either >= 5

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveGeneric
- DeriveLift
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

library:
  source-dirs:
    - utils

executables:
  arith:
    source-dirs: arith
    main: Main.hs
  debruijn:
    source-dirs: debruijn
    main: Main.hs
    dependencies: pizza-g2q-benchmarks
  nqueens:
    source-dirs: nqueens
    main: Main.hs
    dependencies: pizza-g2q-benchmarks
  stringsearch:
    source-dirs: stringsearch
    main: Main.hs
    dependencies: pizza-g2q-benchmarks
